<a href="https://colab.research.google.com/github/chiragdeepmaan/Deep_Learning/blob/main/Encoding_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# one hot encoding
import numpy as np
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=True)

words=np.array([["Dog"],['Cat'],['Cow']])

encoded=encoder.fit_transform(words)
print(encoded.toarray())


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [9]:
# Word2vec
from gensim.models import Word2Vec

sentences=[
    ['i','love','ai'],
    ['Deep','learning','is','fun']
]
model=Word2Vec(
    sentences,
    vector_size=10,
    window=2,
    min_count=1,
)
# print(model.wv.key_to_index)
# print(model.wv.vectors)

print(model.wv['ai'])


[-0.0960355   0.05007293 -0.08759586 -0.04391825 -0.000351   -0.00296181
 -0.0766124   0.09614743  0.04982058  0.09233143]


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 68.2 MB/s eta 0:00:00


In [10]:
import gensim.downloader as api

glove=api.load('glove-wiki-gigaword-100')

print(glove['ai'])

[==================================================] 100.0% 128.1/128.1MB downloaded
[ 0.045108   0.0083492  1.0102     0.038761  -0.30003    0.10823
  0.26686   -0.17974    0.67932   -0.084417   1.062      0.76798
 -0.11493    0.23955    0.077192   0.21395   -0.078771   0.43098
 -0.11153    0.66881    0.36504    0.67177    0.088447   0.62206
 -0.17987    0.86789    0.30889   -0.5903     0.60903   -0.05802
 -0.88395    0.71948    0.89163    0.40236    0.22299    0.096691
 -0.4288    -0.063899   0.40101   -1.1798     0.47658    0.47404
 -0.29498   -0.37048    0.164     -1.0603    -0.33258    0.062372
  0.15286   -0.32601   -0.31319    0.053811  -0.13754    0.0059301
  0.11415   -0.62634    0.68874    0.99291    0.26393    0.92959
 -0.18993    0.22622   -1.0052     0.64348    0.39322    0.76444
 -0.014274   0.39557   -0.11599    0.39713    0.383      0.24651
  0.016404   0.10253   -0.1576     0.60561   -0.11524    0.2444
 -0.14561    0.060226   0.41371   -0.5334    -0.81093   -0.122
 -1.

In [12]:
from sentence_transformers import SentenceTransformer

model=SentenceTransformer('all-miniLM-L6-v2')

embedding= model.encode("Artificial Intelligence")

print(embedding)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

[-2.43510157e-02  1.67067088e-02  3.77205089e-02 -9.16330144e-03
 -3.05845588e-02 -1.70570910e-02  7.42098317e-02  4.57434356e-02
 -9.39854886e-03  9.90001485e-03 -5.70722762e-03  7.58129219e-03
  3.95797230e-02  1.52103491e-02 -8.32180753e-02  1.93442013e-02
 -2.19869036e-02 -3.32064778e-02 -1.81014121e-01 -1.30236059e-01
 -2.25594197e-03  1.33974748e-02 -2.42932308e-02 -3.69969495e-02
  2.02795467e-03  8.56798515e-02  4.72737150e-03 -3.41746700e-03
 -6.03478169e-03 -1.15787201e-01  6.68602064e-02 -1.86576862e-02
  8.78416747e-02 -7.42430612e-03 -9.35673639e-02  6.14009835e-02
 -8.11372548e-02  1.22457668e-02  3.97397168e-02 -2.58957827e-03
 -4.66313474e-02 -8.17789808e-02  3.95028889e-02  1.54695753e-02
  4.36929464e-02  1.03639133e-01 -5.84595799e-02  3.67365479e-02
 -5.27095459e-02  4.05692272e-02 -1.25884563e-01  6.46114815e-03
 -3.58351916e-02 -1.00228488e-02 -2.38814019e-02  4.59325463e-02
  1.45444218e-02  1.94852687e-02  2.84130722e-02 -5.51534295e-02
  2.42295992e-02 -5.30302