<a href="https://colab.research.google.com/github/chiragdeepmaan/Deep_Learning/blob/main/Encoding_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# one hot encoding
import numpy as np
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=True)

words=np.array([["Dog"],['Cat'],['Cow']])

encoded=encoder.fit_transform(words)
print(encoded.toarray())


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [9]:
# Word2vec
from gensim.models import Word2Vec

sentences=[
    ['i','love','ai'],
    ['Deep','learning','is','fun']
]
model=Word2Vec(
    sentences,
    vector_size=10,
    window=2,
    min_count=1,
)
# print(model.wv.key_to_index)
# print(model.wv.vectors)

print(model.wv['ai'])


[-0.0960355   0.05007293 -0.08759586 -0.04391825 -0.000351   -0.00296181
 -0.0766124   0.09614743  0.04982058  0.09233143]


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 68.2 MB/s eta 0:00:00
